on: push

jobs:
  job1:
    name: The build on Linux
    runs-on: ubuntu-latest
    steps:
      
      - name: Install dependencies
        run: |
          pip install PySide6 pyinstaller
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build application
        run: |
          pyinstaller main.spec
          cp ./sever_core/User.db ./dist
      - name: Upload compiled files
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: dist/
      - name: Create ZIP file
        run: |
          mkdir release
          zip -r release/app.zip dist/

      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: app-zip
          path: release/app.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.mybuild }}
        with:
          tag_name: v1.1.1
          release_name: "Release v1.1.1"
          body: "This is the release of version 1.1.1 on Linux:Make the new UI."

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.mybuild }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/app.zip
          asset_name: app.zip
          asset_content_type: application/zip
  job2:
    name: The build on Windows
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          pip install PySide6 pyinstaller
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build application
        run: |
          pyinstaller main.spec
          cp ./sever_core/User.db ./dist
      - name: Upload compiled files
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: dist/
      - name: Create ZIP file
        run: |
          mkdir release
          Compress-Archive -Path dist/* -DestinationPath release/app.zip

      - name: Upload ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: app-zip
          path: release/app.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.mybuild}}
        with:
          tag_name: v1.1.2
          release_name: "Release v1.1.2"
          body: "This is the release of version 1.1.2 on Windows:Make the new UI."

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.mybuild}}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/app.zip
          asset_name: app.zip
          asset_content_type: application/zip
