on: push

jobs:
  job1:
    name: The build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install PySide6 pyinstaller
      - name: Build application
        run: |
          source venv/bin/activate
          ls
          pyinstaller main.spec

  job2:
    name: The build on Windows
    runs-on: windows-latest
    steps:
      - name: Set up Python
        run: |
          python -m venv venv
          venv\Scripts\activate
      - name: Install dependencies
        run: |
          venv\Scripts\activate
          pip install PySide6 pyinstaller
      - name: Build application
        run: |
          venv\Scripts\activate
          pyinstaller main.spec